---
- hosts: 127.0.0.1
  connection: local
#  become: true
  gather_facts: true

  tasks:
    - name: upgrade all packages
      ansible.builtin.package:
        name: "*"
        state: latest
      when: ansible_facts['distribution'] != 'MacOSX'

    - name: Configure Fedora OS
      ansible.builtin.include_tasks: playbooks/fedora.yml
      when: ansible_facts['distribution'] == 'Fedora'

    - name: Configure Debian OS
      ansible.builtin.include_tasks: playbooks/debian.yml
      when: ansible_facts['distribution'] == 'Debian'

    - name: Configure MacOS
      ansible.builtin.include_tasks: playbooks/macos.yml
      when: ansible_facts['distribution'] == 'MacOSX'

    - name: Configure Shell
      block:
        - name: Configure zsh
          ansible.builtin.copy:
            src: "files/{{ ansible_facts['distribution'] }}.zshrc"
            dest: '~/.zshrc'

        - name: Configure Bash
          ansible.builtin.copy:
            src: "files/{{ ansible_facts['distribution'] }}.bashrc"
            dest: '~/.bashrc'

        - name: Configure Vim
          block:
            - name: Install vim-airline plugin
              ansible.builtin.git:
                repo: https://github.com/vim-airline/vim-airline
                dest: '~/.vim/pack/dist/start/vim-airline'

            - name: Configure Vim
              ansible.builtin.copy:
                src: "files/{{ ansible_facts['distribution'] }}.vimrc"
                dest: '~/.vimrc'
