- hosts: 127.0.0.1
  become: true
  vars:
    users:
      - username: ruslan.mamaev

  tasks:
    - name: Remove installed Docker
      dnf:
        name:
          - docker
          - docker-common
          - docker-selinux
          - docker-engine-selinux
          - docker-engine
        state: absent

    - name: Cleanup old Docker dirs
      file:
        path: /var/lib/docker/
        state: absent

    - name: install dnf plugins
      dnf:
        name: dnf-plugins-core
        state: present

    - name: Add Docker Stable Repo
      yum_repository:
        baseurl: https://download.docker.com/linux/fedora/29/x86_64/stable
        enabled: yes
        name: docker-ce-stable
        description: Docker CE Stable - $basearch
        gpgcheck: yes
        gpgkey: https://download.docker.com/linux/fedora/gpg

    - name: Add Docker Edge Repo
      yum_repository:
        baseurl: https://dl.yarnpkg.com/rpm/
        enabled: yes
        name: yarn-repo
        description: Yarn repo
        gpgcheck: yes
        gpgkey: https://dl.yarnpkg.com/rpm/pubkey.gpg

    - name: Update cache
      shell: 'dnf makecache timer'

    - name: Create Docker Group
      group:
        name: docker
        state: present

    - name: Add me to docker group
      user:
        name: "{{ myname }}"
        groups: docker
        append: yes

    - name: "install VS Code repo"
      yum_repository:
        baseurl: "https://packages.microsoft.com/yumrepos/vscode"
        description: "Visual Studio Code repo"
        file: vscode
        gpgcheck: true
        gpgkey: "https://packages.microsoft.com/keys/microsoft.asc"
        name: code

    - name: upgrade all packages
      dnf:
        name: "*"
        state: latest

    - name: Install required packages
      dnf:
        name:
          - make
          - kernel-devel
          - kernel-headers
          - htop
          - gnome-tweak-tool
          - docker-ce
          - the_silver_searcher
          - libselinux-python
          - dkms
          - vim
          - zsh
          - php
          - php-json
          - nodejs
          - yarn
          - python3-virtualenv
          - python-devel
          - code
          - golang
          - groovy
          - postgresql
          - mysql
          - php-simplexml
          - php-xdebug
          - jq
          - postgresql-devel
          - libappindicator-gtk3
          - liberation-fonts
          - mozilla-fira-mono-fonts
          - levien-inconsolata-fonts
          - redhat-lsb-core
        state: present

    - name: Install aws cli
      pip:
          name: awscli
          extra_args: --user
          state: present

    - name: Install python-netaddr
      pip:
          name: netaddr
          extra_args: --user
          state: present

    - name: Start Docker on Boot
      systemd:
        name: docker
        enabled: yes

    - name: Allow to switch keyboard layout with Alt + Shift
      command: gsettings set org.gnome.desktop.wm.keybindings switch-input-source "['<Alt>Shift_L']"

  roles:
    - role: ohmyzsh
