- hosts: 127.0.0.1
  become: true
  vars:
    myname: 'rmamaev'
    rbenv:
      env: user
      version: v1.1.1
      default_ruby: 2.5.3
      rubies:
      - version: 2.5.3
      rbenv_plugins:
        name: "ruby-build"

  roles:
    - role: zzet.rbenv
      rbenv_users:
        ["{{ myname }}"]
    - role: gantsign.oh-my-zsh
      users:
        - username: rmamaev

  tasks:
    - name: Remove installed Docker
      dnf:
        name:
          - docker
          - docker-common
          - docker-selinux
          - docker-engine-selinux
          - docker-engine
        state: absent

    - name: Cleanup old Docker dirs
      file:
        path: /var/lib/docker/
        state: absent

    - name: install dnf plugins
      dnf:
        name: dnf-plugins-core
        state: present

    - name: Add Docker Stable Repo
      yum_repository:
        baseurl: https://download.docker.com/linux/fedora/27/x86_64/stable
        enabled: yes
        name: docker-ce-stable
        description: Docker CE Stable - $basearch
        gpgcheck: yes
        gpgkey: https://download.docker.com/linux/fedora/gpg

    - name: Add Docker Edge Repo
      yum_repository:
        baseurl: https://dl.yarnpkg.com/rpm/
        enabled: yes
        name: yarn-repo
        description: Yarn repo
        gpgcheck: yes
        gpgkey: https://dl.yarnpkg.com/rpm/pubkey.gpg

    - name: Add Yarn Repo
      yum_repository:
        baseurl: https://download.docker.com/linux/fedora/27/x86_64/edge
        enabled: yes
        name: docker-ce-edge
        description: Docker CE Edge - $basearch
        gpgcheck: yes
        gpgkey: https://download.docker.com/linux/fedora/gpg

    - name: Update cache
      shell: 'dnf makecache timer'

    - name: Create Docker Group
      group:
        name: docker
        state: present

    - name: Add me to docker group
      user:
        name: "{{ myname }}"
        groups: docker
        append: yes

    - name: "install VS Code repo"
      yum_repository:
        baseurl: "https://packages.microsoft.com/yumrepos/vscode"
        description: "Visual Studio Code repo"
        file: vscode
        gpgcheck: true
        gpgkey: "https://packages.microsoft.com/keys/microsoft.asc"
        name: code

    - name: upgrade all packages
      dnf:
        name: "*"
        state: latest

    - name: Install required packages
      dnf:
        name:
          - make
          - kernel-devel
          - kernel-headers
          - htop
          - gnome-tweak-tool
          - keepassx
          - preload
          - docker-ce
          - the_silver_searcher
          - libselinux-python
          - dkms
          - vim
          - zsh
          - php
          - php-json
          - nodejs
          - yarn
          - python3-virtualenv
          - python-devel
          - code
          - golang
          - groovy
          - postgresql
          - mysql
          - php-simplexml
          - php-xdebug
          - jq
        state: present

    - name: Install aws cli
      pip:
          name: awscli
          extra_args: --user
          
    - name: Install python-netaddr
      pip:
          name: netaddr
          extra_args: --user
          
    - name: Start Docker on Boot
      systemd:
        name: docker
        enabled: yes

    - name: Create bin dir
      file:
        path: "{{ lookup('env','HOME') }}/.local/bin"
        state: directory

    - name: Install Terraform
      unarchive:
        remote_src: yes
        src: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"
        dest: "{{ lookup('env','HOME') }}/.local/bin"

    - name: Allow to switch keyboard layout with Alt + Shift
      command: gsettings set org.gnome.desktop.wm.keybindings switch-input-source "['<Alt>Shift_L']"
