---
- hosts: 127.0.0.1
  connection: local
  gather_facts: true

  tasks:
    - name: upgrade all packages
      ansible.builtin.package:
        name: "*"
        state: latest
      when: ansible_facts['distribution'] != 'MacOSX'

    - name: Configure Fedora OS
      ansible.builtin.include_tasks: playbooks/fedora.yml
      when: ansible_facts['distribution'] == 'Fedora'

    - name: Configure Debian OS
      ansible.builtin.include_tasks: playbooks/debian.yml
      when: ansible_facts['distribution'] == 'Debian'

    - name: Configure MacOS
      ansible.builtin.include_tasks: playbooks/macos.yml
      when: ansible_facts['distribution'] == 'MacOSX'

    - name: Configure Environment
      block:
        - name: Configure zsh
          ansible.builtin.copy:
            src: "files/{{ ansible_facts['distribution'] }}.zshrc"
            dest: '~/.zshrc'

        - name: Configure zsh
          block:
          - name: Create zsh completions dir
            ansible.builtin.file:
              name: '~/.oh-my-zsh/completions'
              state: directory
              mode: '0755'

          - name: Download kns completions
            ansible.builtin.get_url:
              url: https://raw.githubusercontent.com/ahmetb/kubectx/master/completion/_kubens.zsh
              dest: '~/.oh-my-zsh/completions/_kubens.zsh'
              mode: '0755'

          - name: Download ktx completions
            ansible.builtin.get_url:
              url: https://raw.githubusercontent.com/ahmetb/kubectx/master/completion/_kubectx.zsh
              dest: '~/.oh-my-zsh/completions/_kubectx.zsh'
              mode: '0755'

        - name: Configure Bash
          ansible.builtin.copy:
            src: "files/{{ ansible_facts['distribution'] }}.bashrc"
            dest: '~/.bashrc'

        - name: Setup Terraform env
          ansible.builtin.file:
            name: '~/.terraform.d/plugin-cache'
            state: directory

        - name: Configure Vim
          block:
            - name: Install vim-airline plugin
              ansible.builtin.git:
                repo: https://github.com/vim-airline/vim-airline
                dest: '~/.vim/pack/dist/start/vim-airline'

            - name: Configure Vim
              ansible.builtin.copy:
                src: "files/{{ ansible_facts['distribution'] }}.vimrc"
                dest: '~/.vimrc'
