- hosts: 127.0.0.1
  connection: local
  become: true


  tasks:
    - name: Create Docker Group
      group:
        name: docker
        state: present

    - name: Add me to docker group
      user:
        name: "{{ username }}"
        groups: docker
        append: yes

    - name: upgrade all packages
      package:
        name: "*"
        state: latest

    - name: Configure Fedora OS
      block:
      - name: install dnf plugins
        dnf:
          name: dnf-plugins-core
          state: present

      - name: Remove installed Docker
        dnf:
          name:
            - docker
            - docker-common
            - docker-selinux
            - docker-engine-selinux
            - docker-engine
            - docker-client
            - docker-client-latest
            - docker-latest
            - docker-latest-logrotate
            - docker-logrotate
          state: absent

      - name: Cleanup old Docker dirs
        file:
          path: /var/lib/docker/
          state: absent

      - name: Add Docker Stable Repo
        yum_repository:
          baseurl: https://download.docker.com/linux/fedora/29/x86_64/stable
          enabled: yes
          name: docker-ce-stable
          description: Docker CE Stable - $basearch
          gpgcheck: yes
          gpgkey: https://download.docker.com/linux/fedora/gpg

      - name: Add Docker Edge Repo
        yum_repository:
          baseurl: https://dl.yarnpkg.com/rpm/
          enabled: yes
          name: yarn-repo
          description: Yarn repo
          gpgcheck: yes
          gpgkey: https://dl.yarnpkg.com/rpm/pubkey.gpg

      - name: Update cache
        shell: 'dnf makecache timer'

      - name: "install VS Code repo"
        yum_repository:
          baseurl: "https://packages.microsoft.com/yumrepos/vscode"
          description: "Visual Studio Code repo"
          file: vscode
          gpgcheck: true
          gpgkey: "https://packages.microsoft.com/keys/microsoft.asc"
          name: code

      - name: Install required packages
        dnf:
          name:
            - make
            - kernel-devel
            - kernel-headers
            - htop
            - gnome-tweak-tool
            - docker-ce
            - the_silver_searcher
            - libselinux-python
            - dkms
            - vim
            - zsh
            - php
            - php-json
            - python3-virtualenv
            - python-devel
            - code
            - golang
            - groovy
            - postgresql
            - mysql
            - php-simplexml
            - php-xdebug
            - jq
            - postgresql-devel
            - libappindicator-gtk3
            - liberation-fonts
            - mozilla-fira-mono-fonts
            - levien-inconsolata-fonts
            - redhat-lsb-core
          state: present
      when: ansible_facts['distribution'] == 'Fedora'

    - name: Configure Debian OS
      block:
      - name: Remove installed Docker
        apt:
          name:
            - docker
            - docker-engine
            - docker.io
            - containerd
            - runc
          state: absent

      - name: Install packages for apt
        apt:
          name:
            - apt-transport-https
            - ca-certificates
            - curl
            - gnupg2
            - software-properties-common
          update_cache: yes
          state: present

      - name: Add an Docker signing key, will not download if present
        apt_key:
          url: https://download.docker.com/linux/debian/gpg
          state: present

      - name: Add an VSCode signing key, will not download if present
        apt_key:
          url: "https://packages.microsoft.com/keys/microsoft.asc"
          state: present

      - name: Add Docker Stable Repo
        apt_repository:
          repo: "deb [arch=amd64] https://download.docker.com/linux/debian buster stable"
          filename: docker-ce-stable

      - name: "install VS Code repo"
        apt_repository:
          repo: "deb https://packages.microsoft.com/repos/vscode stable main"
          filename: vscode

      - name: Install required packages
        apt:
          name:
            - make
            - linux-libc-dev
            - htop
            - gnome-tweak-tool
            - docker-ce
            - docker-ce-cli
            - containerd.io
            - silversearcher-ag
            - dkms
            - vim
            - zsh
            - php
            - php-json
            - python3-virtualenv
            - python-dev
            - python3-dev
            - code
            - golang
            - groovy
            - php-simplexml
            - php-xdebug
            - jq
            - fonts-liberation
            - fonts-firacode
            - fonts-inconsolata
            - pip
          state: present
      when: ansible_facts['distribution'] == 'Debian'

    - name: Install aws cli
      pip:
          name: awscli
          extra_args: --user
          state: present

    - name: Start Docker on Boot
      systemd:
        name: docker
        enabled: yes

  roles:
    - role: ohmyzsh
      users:
        - username: "{{ username }}"
