---
- name: Configure Fedora OS
  block:
    - name: install dnf plugins
      dnf:
        name: dnf-plugins-core
        state: present

    - name: Remove installed Docker
      dnf:
        name:
          - docker
          - docker-common
          - docker-selinux
          - docker-engine-selinux
          - docker-engine
          - docker-client
          - docker-client-latest
          - docker-latest
          - docker-latest-logrotate
          - docker-logrotate
        state: absent

    - name: Cleanup old Docker dirs
      file:
        path: /var/lib/docker/
        state: absent

    - name: Update cache
      shell: 'dnf makecache timer'

    - name: "install VS Code repo"
      yum_repository:
        baseurl: "https://packages.microsoft.com/yumrepos/vscode"
        description: "Visual Studio Code repo"
        file: vscode
        gpgcheck: true
        gpgkey: "https://packages.microsoft.com/keys/microsoft.asc"
        name: code

    - name: "install Kubernetes repo"
      yum_repository:
        baseurl: "https://pkgs.k8s.io/core:/stable:/v1.28/rpm/"
        description: "Kubernetes Package Repo"
        file: kubernetes
        gpgcheck: true
        gpgkey: "https://pkgs.k8s.io/core:/stable:/v1.28/rpm/repodata/repomd.xml.key"
        name: kubernetes

    - name: Install required packages
      dnf:
        name:
          - make
          - kernel-devel
          - kernel-headers
          - htop
          - gnome-tweak-tool
          - the_silver_searcher
          - python3-libselinux
          - dkms
          - vim
          - zsh
          - python-devel
          - code
          - golang
          - jq
          - liberation-fonts
          - mozilla-fira-mono-fonts
          - levien-inconsolata-fonts
          - redhat-lsb-core
          - tmux
          - podman
          - buildah
          - kubectl
        state: present

    - name: Install kubectx & kubens tools
      block:
        - name: Install kubectx
          ansible.builtin.get_url:
            url: https://raw.githubusercontent.com/ahmetb/kubectx/master/kubectx
            dest: "~/.local/bin"
            mode: '0755'

        - name: Install kubens
          ansible.builtin.get_url:
            url: https://raw.githubusercontent.com/ahmetb/kubectx/master/kubens
            dest: "~/.local/bin"
            mode: '0755'

  when: ansible_facts['distribution'] == 'Fedora'
